Repository ethereum-optimism/contracts, pull requests merged in 2020-12, with the labels that each got.

#108 remove unused stateTransitionIndex
  .gitignore
  contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
  contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol
  contracts/optimistic-ethereum/OVM/precompiles/OVM_SequencerEntrypoint.sol
  contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
  contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
  contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitionerFactory.sol
  contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol
  contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol
  contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitionerFactory.sol
  contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
  contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_Bytes32Utils.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol
  package.json
  test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
  test/contracts/OVM/execution/OVM_StateManager.spec.ts
  test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
  test/contracts/OVM/verification/OVM_StateTransitioner.spec.ts
  test/contracts/libraries/rlp/Lib_RLPWriter.spec.ts
  test/helpers/constants.ts
Labels: Breaks: Fraud Prover, Category: Cleanup, Priority: Needs Assignment, Status: Ready for Merge

#109 createEOA setAccountNonce to 0
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
  test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATEEOA.spec.ts
Labels: Category: Audit Fix, Priority: Critical, Status: Ready for Merge

#113 Minor deployment updates (for fraud prover)
  src/contract-deployment/config.ts
  src/contract-dumps.ts
  test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
  test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
  test/contracts/libraries/rlp/Lib_RLPWriter.spec.ts
  test/contracts/libraries/trie/Lib_MerkleTrie.spec.ts
Labels: Blocks: Fraud Prover, Priority: High, Status: Needs Review

#117 require relayer fee transfer success
  contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
  test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
Labels: Category: Audit Fix, Priority: Medium, Status: Ready for Merge

#118 Adds an ovm compilation plugin, compiles into artifacts and artifacts/ovm
  buidler.config.ts
  contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
  contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
  contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
  contracts/optimistic-ethereum/iOVM/bridge/iOVM_L2CrossDomainMessenger.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L1MessageSender.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L2ToL1MessagePasser.sol
  contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
  contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol
  contracts/optimistic-ethereum/libraries/resolver/Lib_Ownable.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_ReentrancyGuard.sol
  package.json
  plugins/buidler/ovm-compiler.ts
  src/contract-defs.ts
  tsconfig.json
  yarn.lock
Labels: Category: Enhancement, Priority: High, Status: Ready for Merge

#135 Temporarily disable gas checks
  contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
  test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
Labels: Priority: Critical, Status: Needs Review

#130 Fix typos
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
  contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol
  contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol
Labels: Category: Audit Fix, Priority: Low, Status: Ready for Merge

#129 Remove unused imports
  contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
Labels: Category: Audit Fix, Priority: Low, Status: Ready for Merge

#128 Simplify Casting
  contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol
Labels: Category: Audit Fix, Priority: Low, Status: Changes Requested

#114 Move ganache-core to main deps
  package.json
Labels: Category: Cleanup, Priority: Low, Status: Needs Review

#145 Add StateBatchDeleted event to SCC
  contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
Labels: Category: Enhancement, Priority: High, Status: Needs Review

#142 Bump version to .14
  package.json
Labels: Category: Cleanup, Priority: Low, Status: Needs Review

#131 Remove unused function parameter
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
Labels: Category: Audit Fix, Priority: Low, Status: Ready for Merge

#151 Separates storage from SCC and CTC
  contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol
  contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_Math.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
  contracts/test-libraries/utils/TestLib_RingBuffer.sol
  package.json
  src/contract-deployment/config.ts
  src/contract-deployment/deploy.ts
  test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
  test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts
Labels: Priority: High, Status: Needs Review

#98 Update EM comment
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
Labels: Category: Comments, Priority: Low, Status: Ready for Merge

#112 uint -> uint256
  contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/OVM/verification/OVM_FraudContributor.sol
  contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L2ToL1MessagePasser.sol
  contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
  contracts/optimistic-ethereum/libraries/rlp/Lib_RLPWriter.sol
  contracts/test-helpers/Helper_GasMeasurer.sol
  contracts/test-helpers/TestERC20.sol
  contracts/test-libraries/rlp/TestLib_RLPWriter.sol
Labels: Category: Audit Fix, Status: Ready for Merge

#119 Enable Deployer Whitelist
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
  contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol
  contracts/test-helpers/Helper_TestRunner.sol
  test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATE.spec.ts
  test/helpers/codec/revert-flags.ts
  test/helpers/test-runner/test-runner.ts
  test/helpers/test-runner/test.types.ts
Labels: Category: Audit Fix, Priority: High, Status: Mergeable; Breaking

#140 Restrict StateTransitionerFactory
  contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitionerFactory.sol
  src/contract-deployment/config.ts
  test/contracts/OVM/verification/OVM_StateTransitionerFactory.spec.ts
Labels: Category: Audit Fix, Status: Needs Review

#93 CTC Chain Monotonicity Fixes
  contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
  src/contract-deployment/config.ts
  src/contract-dumps.ts
  test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
  test/helpers/constants.ts
  test/helpers/utils/eth-time.ts
Labels: Breaks: Batch Submitter, Category: Audit Fix, Priority: Medium, Status: Mergeable; Breaking, breaks:Deployment

#148 Adds river's new Merkle tree implementation, with some cleanup
  contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_MerkleTree.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_MerkleUtils.sol
  contracts/test-libraries/utils/TestLib_MerkleTree.sol
  contracts/test-libraries/utils/TestLib_MerkleUtils.sol
  package.json
  test/contracts/libraries/utils/Lib_MerkleTree.spec.ts
  yarn.lock
Labels: Blocks: Fraud Prover

#94 Fix run gas Lower Bound
  bin/deploy.js
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
  test/contracts/OVM/execution/OVM_ExecutionManager/run.spec.ts
  test/helpers/test-runner/test-runner.ts
  test/helpers/test-runner/test.types.ts
Labels: Breaks: Geth L2, Category: Audit Fix, Priority: Critical, Status: Needs Review

#122 update solidity version to ^0.7.0
  buidler.config.ts
  contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
  contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
  contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
  contracts/optimistic-ethereum/OVM/precompiles/OVM_ETH.sol
  contracts/optimistic-ethereum/OVM/precompiles/OVM_L2ToL1MessagePasser.sol
  contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
  contracts/optimistic-ethereum/iOVM/bridge/iOVM_L1CrossDomainMessenger.sol
  contracts/optimistic-ethereum/iOVM/bridge/iOVM_L2CrossDomainMessenger.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
  contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_DeployerWhitelist.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_ERC20.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L1MessageSender.sol
  contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L2ToL1MessagePasser.sol
  contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol
  contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol
  contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
  contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
  contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol
  contracts/optimistic-ethereum/libraries/resolver/Lib_Ownable.sol
  contracts/optimistic-ethereum/libraries/trie/Lib_SecureMerkleTrie.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_ReentrancyGuard.sol
  test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATEEOA.spec.ts
Labels: Category: Audit Fix, Priority: Low, Status: Ready for Merge
