Repository ethereum-optimism/contracts, pull requests merged in 2021-03, with the labels that each got.

#297 Remove gas estimators from gateway interface
  contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L1TokenGateway.sol
  contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L2DepositedToken.sol
  contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1TokenGateway.sol
  contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2DepositedToken.sol
Labels: Status: Ready for Merge

#289 cleanup: Minor cleanup to state manager
  contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol
Labels: Status: Ready for Merge

#294 dev: Create CODEOWNERS
  .github/CODEOWNERS
Labels: Status: Ready for Merge

#293 cleanup: Bytes32Utils
  contracts/optimistic-ethereum/libraries/utils/Lib_Bytes32Utils.sol
Labels: Status: Ready for Merge

#290 cleanup: Minor cleanups for StateManagerFactory
  contracts/optimistic-ethereum/OVM/execution/OVM_StateManagerFactory.sol
Labels: Status: Ready for Merge

#291 cleanup: Proxy_EOA
  contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol
Labels: Status: Ready for Merge

#292 cleanup: ECDSAContractAccount
  contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
Labels: Status: Ready for Merge

#287 cleanup: Simplify OVMCodec a bit
  contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
Labels: Status: Ready for Merge

#228 feat: CanonicalTransactionChain gas optimizations
  contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
  contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol
  contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol
  contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
  package.json
  test/contracts/OVM/chain/OVM_CanonicalTransactionChain.gas.spec.ts
  test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
  yarn.lock
Labels: Category: Enhancement, Priority: High, Status: Needs Review

#252 Separate Out CTC and SCC Proposer Roles
  contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
  contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol
  src/contract-deployment/config.ts
  test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts
  test/contracts/mockOVM/verification/mockOVM_BondManager.spec.ts
Labels: Status: Ready for Merge

#308 Eliminate EM.safeCREATE logic
  contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
  contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
  contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol
  contracts/optimistic-ethereum/libraries/utils/Lib_ErrorUtils.sol
  contracts/optimistic-ethereum/libraries/wrappers/Lib_SafeExecutionManagerWrapper.sol
  contracts/optimistic-ethereum/mockOVM/accounts/mockOVM_ECDSAContractAccount.sol
  contracts/test-helpers/Helper_TestRunner.sol
  test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
  test/contracts/OVM/execution/OVM_ExecutionManager.gas-spec.ts
  test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATE.spec.ts
  test/helpers/codec/revert-flags.ts
  test/helpers/dummy/bytecode.ts
  test/helpers/test-runner/test-runner.ts
  test/helpers/test-runner/test.types.ts
  test/helpers/utils/sol-utils.ts
Labels: Category: Enhancement, Priority: High, Status: Changes Requested

#343 fix: Stricter RLP boolean checking
  contracts/optimistic-ethereum/libraries/rlp/Lib_RLPReader.sol
  test/data/json/libraries/rlp/Lib_RLPReader.test.json
Labels: Priority: Low, Status: Needs Review
